### ISSUE TITLE
[RFC] 底层协议无关

### ISSUE THREAD

**Issue by hyj1991** [artusjs/spec#1]
讨论下怎么抽象交互模型，下面是我目前的一些想法。

底层协议无关并不是没有任何限制，这里可能依旧主要面向 C/S 的交互场景（或者有更好的想法）：
* 请求 - 响应模型
* 单独的请求模型（无响应）
* 单独的响应模型（无请求）

目前的 C/S 的交互场景自身是存在一些可以抽象出来的公共特征，以及流水线式的逻辑处理天然有统一的切面处理需求，结合目前版本的实践，进一步进行可扩展的设计：
* 抽象 BaseContext
  * HttpContext / RpcContext / UdpContext / WebSocketContext / ThriftContext 根据协议自行扩展
* 抽象 BaseTrigger + 洋葱中间件模型
  * Trigger 作为中间件入口触发器，不同协议可以自行扩展加一些定制信息

**Comment by JerrysShan** [comment]
每种协议差别的地方就是入口，感觉可以把协议无关的地方抽象出来，

- BassFramework
   - HttpFramework
     - HttpContext 
   - RpcFramework
     - RpcContext
   - WebSocketFramework
     - WebSocketContext
 
而其他的部分，比如service ，中间件，插件，AOP处理这些基本上都可以复用，但是可能也有一些特例和协议相关

**Comment by hyj1991** [comment]
> 每种协议差别的地方就是入口，感觉可以把协议无关的地方抽象出来，

这里我的想法是设计一个 BaseTrigger 作为入口，框架的话是上层封装了，我们可以把框架内核设计的尽量轻量，各种协议围绕框架内核做对应协议下的封装

**Comment by fengmk2** [comment]
CS 交互抽象，可以参考 GRPC 的，很有启发 https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-life-cycle
通过4种 RPC 类型抽象，就将所有 CS 交互场景描述完备了。

**Comment by hyj1991** [comment]
> CS 交互抽象，可以参考 GRPC 的，很有启发 https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-life-cycle 通过4种 RPC 类型抽象，就将所有 CS 交互场景描述完备了。

这个很赞，研究下可以拿来加到我们的 spec 里

**Comment by fengmk2** [comment]
https://docs.google.com/presentation/d/1sRBynObD62EVbd5GdeACH2K36HxcGF6LgzcNFqbQDHc/edit#slide=id.gf99e0be469_0_2
连事件都 await 了

**Comment by noahziheng** [comment]
Trigger 部分已写入 Core Spec
