### ISSUE TITLE
文档中的图片无法正确显示

### ISSUE THREAD

**Issue by liuhanqu** [artusjs/spec#15]
如题。

**Comment by noahziheng** [comment]
能举个栗子嘛，哪张有问题

**Comment by liuhanqu** [comment]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/13450124/159103826-e7d74e90-3b00-4a13-9dab-3681f1aa74c7.png">

**Comment by noahziheng** [comment]
检查了一波，现在应该是OK的了
