### ISSUE TITLE
[RFC] 原生 TS  开发，希望提供静态语言的开发体验

### ISSUE THREAD

**Issue by JerrysShan** [artusjs/spec#2]
减少属性动态挂载，开发时类型显式声明

**Comment by hyj1991** [comment]
像路由这种也需要类型支持 `/path/:params`

**Comment by hyj1991** [comment]
其实 TS 的设计放到 spec 中，不知道要怎么描述

**Comment by JerrysShan** [comment]
> 其实 TS 的设计放到 spec 中，不知道要怎么描述对应的 spec 内容

在设计其他模块的spec时，作为考虑项，要为开发体验负责

**Comment by hyj1991** [comment]
另外一个问题是，我们在 Egg 3 中还是会在编程界面中透出 js 的开发方式给用户，这部分用户的习惯得保留，如果使用 ts 4.5 中的 `"type": "module"`，感觉可以直接 target 到 esm 去

**Comment by XadillaX** [comment]
我个人其实也是比较偏向于框架 core 仍然是 JavaScript，也继续保留 JavaScript，然后再外加一层好用的 TypeScript 支持。

**Comment by fengmk2** [comment]
https://github.com/farrow-js/farrow 领路者

**Comment by i5ting** [comment]
> https://github.com/farrow-js/farrow

貌似只有http.get('/get0/<arg0:int>?<arg1:int>')这个有些新意

**Comment by noahziheng** [comment]
现已明确 Core 使用 TypeScript 开发，Spec 预留 TS 特性支持
