### ISSUE TITLE
[RFC] 插件能力设计及生态

### ISSUE THREAD

**Issue by BeAce** [artusjs/spec#3]
## 能力设计
- **业务逻辑层面**
    - 插件应该是一个完整的应用 `min-application`，允许参与路由控制、支持业务逻辑、插件中使用中间件等。
- **插件使用**
     - 保持可插拔的特性，开发者应该能够在框架层面控制插件的 `enable` 和 `disable`。
     - 个人认为插件可以相互保持依赖关系（**执行顺序的依赖关系**），但是要降低互相引用，保持相对独立（这里可能是个值得讨论的点）。
     - 屏蔽内部实现细节，只对外暴露整体，面向开发者一键使用。
- **插件API**。
    - 涉及到插件开发，需要存在这样一个 `PluginBase` 基类，入口类似的 `apply` 、`create` 方法。
    - 同样的，如果是一个完备的应用，需要具有 `/service` `/middleware` 能力

## 插件生态
- **插件开发**
  - 降低插件开发门槛，保持插件开发的透明度。提供一套完整的插件 `boilerplate` 规范，以及开发插件注入、测试、集成方法，甚至包含插件发布的工具链。
- **插件市场**
  - 搭建插件市场，类似的 [gatsbyjs plugin](https://www.gatsbyjs.com/plugins/gatsby-source-filesystem) 形式。进行一些归类，大类上可以分为官方及社区。
  - 必要时在业务框架中内置核心或者说常用插件，也需要支持用户自建私有插件库。
  - 搭建插件社区，透露一些插件使用频率（npm 下载量、issue 个数、活跃程度等），官方可以提供一定程度的插件审核、review、推广，这块偏运营。

**Comment by noahziheng** [comment]
插件配置方式（需要讨论）

## 配置入口类（用户 import） \*\*\*

```typescript
// config/config.default.ts
import RedisPlugin from '@conf-js/redis'

export default {
    plugins: [
        RedisPlugin
    ]
};
```

## 配置插件名（框架实现 Plugin Loader） \*\*

```typescript
// config/config.default.ts
export default {
    plugins: [
        '@conf-js/redis'
    ]
};
```

## 独立配置文件（Egg 模式） \*

考虑仅用于向下兼容 (?)

```typescript
// config/plugin.ts
export default {
    redis: {
        enable: true,
        options: {
            host: '::1'
        }
    }
}
```

**Comment by noahziheng** [comment]
补充点1(from @hyj1991 in yuque): https://www.yuque.com/confswg/mind-storm/eqv3x1#comment-21810921

考虑插件 / Layer 加载机制允许开源工程被私有化部署时执行灵活替换的机制

/cc @BeAce @JerrysShan

**Comment by noahziheng** [comment]
Plugin 部分已写入 Core Spec
