### ISSUE TITLE
[RFC] 错误信息标准化 & 友好错误提示

### ISSUE THREAD

**Issue by noahziheng** [artusjs/spec#4]
## 特性描述

- 提供统一机制给框架 Core、生态插件，按规范(1)抛错
- 错误信息由 Logger 按规范(2)打印
- 提供统一平台按规范(3)接受错误信息注册，并供查询

## 产出内容

- 统一错误抛出 API  *规范(1)*
- 错误信息 API  *规范(2)*
- 平台错误记录标准格式  *规范(3)*

**Comment by XadillaX** [comment]
日志和其它一些规范规范可以引用 https://opentelemetry.io/

**Comment by czy88840616** [comment]
opentelemetry.io 不太一样吧，并不是日志规范，只是一套链路追踪，metrics 相关的，日志打点是另一套。

**Comment by noahziheng** [comment]
Exception 部分已写入 Core Spec
