### ISSUE TITLE
[RFC] 多样化构建结果

### ISSUE THREAD

**Issue by noahziheng** [artusjs/spec#6]
## 特性描述

- 使用 tsc/不构建 形式，产出传统 Node.js 工程
- 通过 swc/esbuild 等工具，加速构建环节/本地开发，产出传统 Node.js  工程
- 通过 webpack 复用前端生态，产出单文件，用于 Serverless/WebAssembly 等场景
- 以上特性通过 CLI 的配置文件决定

```typescript
// framework-cli.config.ts
export default {
   port: 3000,
   build: {
     	 engine: 'swc',
       bundle: true, // Single file bundle
   },
   devServer: {
       hmr: true,
   }
}
```

**Comment by noahziheng** [comment]
补充点1(from @hyj1991 in yuque): 支持对构建产物进行加密，用于私有化场景

**Comment by JerrysShan** [comment]
打包工具可以考虑下 [ncc](https://github.com/vercel/ncc) 和 [nft](https://github.com/vercel/nft)

**Comment by noahziheng** [comment]
初步结论：该部分由上层框架自定义，后续规范再讨论
